variable "project_id" {}
variable "vpc_name" {}
variable "bastion_subnet" {}
variable "bastion_region" {}
variable "bastion_cidr" {}
variable "private_subnet" {}
variable "private_region" {}
variable "private_cidr" {}
variable "bastion_firewall_name" {}
variable "bastion_network_tags" {}
variable "private_firewall_name" {}
variable "private_network_tags" {}
